homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.455841
  longitude: 7.797736
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 266
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Packages
  packages: !include_dir_named packages
  
discovery:

lovelace:
  mode: yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_api_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Recorder
recorder:
  purge_keep_days: 10

